package kasityologi.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kasityologi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 14:43:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MateriaalitTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista52 
   * @throws SailoException when error
   */
  @Test
  public void testPoista52() throws SailoException {    // Materiaalit: 52
    Materiaalit matskut = new Materiaalit(); 
    Materiaali kangas21 = new Materiaali(); kangas21.taytaMateriaaliTiedoilla(2); 
    Materiaali kangas11 = new Materiaali(); kangas11.taytaMateriaaliTiedoilla(1); 
    Materiaali kangas22 = new Materiaali(); kangas22.taytaMateriaaliTiedoilla(2); 
    Materiaali kangas12 = new Materiaali(); kangas12.taytaMateriaaliTiedoilla(1); 
    Materiaali kangas23 = new Materiaali(); kangas23.taytaMateriaaliTiedoilla(2); 
    matskut.lisaa(kangas21); 
    matskut.lisaa(kangas11); 
    matskut.lisaa(kangas22); 
    matskut.lisaa(kangas12); 
    assertEquals("From: Materiaalit line: 65", false, matskut.poista(kangas23)); assertEquals("From: Materiaalit line: 65", 4, matskut.getLkm()); 
    assertEquals("From: Materiaalit line: 66", true, matskut.poista(kangas11)); assertEquals("From: Materiaalit line: 66", 3, matskut.getLkm()); 
    List<Materiaali> h = matskut.annaMateriaalit(1); 
    assertEquals("From: Materiaalit line: 68", 1, h.size()); 
    assertEquals("From: Materiaalit line: 69", kangas12, h.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaMateriaalit217 */
  @Test
  public void testAnnaMateriaalit217() {    // Materiaalit: 217
    Materiaalit materiaalit = new Materiaalit(); 
    Materiaali kangas21 = new Materiaali(2); materiaalit.lisaa(kangas21); 
    Materiaali kangas11 = new Materiaali(1); materiaalit.lisaa(kangas11); 
    Materiaali kangas22 = new Materiaali(2); materiaalit.lisaa(kangas22); 
    Materiaali kangas12 = new Materiaali(1); materiaalit.lisaa(kangas12); 
    Materiaali kangas23 = new Materiaali(2); materiaalit.lisaa(kangas23); 
    Materiaali kangas51 = new Materiaali(5); materiaalit.lisaa(kangas51); 
    List<Materiaali> loytyneet; 
    loytyneet = materiaalit.annaMateriaalit(3); 
    assertEquals("From: Materiaalit line: 230", 0, loytyneet.size()); 
    loytyneet = materiaalit.annaMateriaalit(1); 
    assertEquals("From: Materiaalit line: 232", 2, loytyneet.size()); 
    assertEquals("From: Materiaalit line: 233", true, loytyneet.get(0) == kangas11); 
    assertEquals("From: Materiaalit line: 234", true, loytyneet.get(1) == kangas12); 
    loytyneet = materiaalit.annaMateriaalit(5); 
    assertEquals("From: Materiaalit line: 236", 1, loytyneet.size()); 
    assertEquals("From: Materiaalit line: 237", true, loytyneet.get(0) == kangas51); 
  } // Generated by ComTest END
}