package kasityologi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.assertEquals;

import org.junit.Test;

// Generated by ComTest END
import kasityologi.Materiaali;

/**
 * Test class made by ComTest
 * @version 2020.04.01 20:47:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MateriaaliTest {



  // Generated by ComTest BEGIN
  /** testToString90 */
  @Test
  public void testToString90() {    // Materiaali: 90
    Materiaali materiaali = new Materiaali(); 
    materiaali.parse("   2   |  villalanka  |   musta    "); 
    assertEquals("From: Materiaali line: 93", "2|villalanka|musta", materiaali.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse119 */
  @Test
  public void testParse119() {    // Materiaali: 119
    Materiaali materiaali = new Materiaali(); 
    materiaali.parse("   2   |  villalanka  |   musta    "); 
    assertEquals("From: Materiaali line: 122", 2, materiaali.getProjektiId()); 
    assertEquals("From: Materiaali line: 123", "2|villalanka|musta", materiaali.toString()); 
  } // Generated by ComTest END
}