package kasityologi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;

// Generated by ComTest END
import kasityologi.Projekti;
import kasityologi.Projektit;
import kasityologi.SailoException;

/**
 * Test class made by ComTest
 * @version 2020.04.01 20:40:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ProjektitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa37 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa37() throws SailoException {    // Projektit: 37
    Projektit projektit = new Projektit(); 
    Projekti sukka1 = new Projekti(), sukka2 = new Projekti(); 
    assertEquals("From: Projektit line: 41", 0, projektit.getLkm()); 
    projektit.lisaa(sukka1); assertEquals("From: Projektit line: 42", 1, projektit.getLkm()); 
    projektit.lisaa(sukka2); assertEquals("From: Projektit line: 43", 2, projektit.getLkm()); 
    projektit.lisaa(sukka1); assertEquals("From: Projektit line: 44", 3, projektit.getLkm()); 
    assertEquals("From: Projektit line: 45", sukka1, projektit.anna(0)); 
    assertEquals("From: Projektit line: 46", sukka2, projektit.anna(1)); 
    assertEquals("From: Projektit line: 47", sukka1, projektit.anna(2)); 
    assertEquals("From: Projektit line: 48", false, projektit.anna(1) == sukka1); 
    assertEquals("From: Projektit line: 49", true, projektit.anna(1) == sukka2); 
    try {
    assertEquals("From: Projektit line: 50", sukka1, projektit.anna(3)); 
    fail("Projektit: 50 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    projektit.lisaa(sukka1); assertEquals("From: Projektit line: 51", 4, projektit.getLkm()); 
    projektit.lisaa(sukka1); assertEquals("From: Projektit line: 52", 5, projektit.getLkm()); 
    projektit.lisaa(sukka1); 
  } // Generated by ComTest END
}