package kasityologi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.assertEquals;

import org.junit.Test;

// Generated by ComTest END
import kasityologi.Projekti;

/**
 * Test class made by ComTest
 * @version 2020.02.24 18:35:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ProjektiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi32 */
  @Test
  public void testRekisteroi32() {    // Projekti: 32
    Projekti sukka1 = new Projekti(); 
    assertEquals("From: Projekti line: 34", 0, sukka1.getProjektiId()); 
    sukka1.rekisteroi(); 
    Projekti sukka2 = new Projekti(); 
    sukka2.rekisteroi(); 
    int n1 = sukka1.getProjektiId(); 
    int n2 = sukka2.getProjektiId(); 
    assertEquals("From: Projekti line: 40", n2-1, n1); 
  } // Generated by ComTest END
}